import { Router } from "express";
import { studentRoute } from "./students.js";
import { courseRoute } from "./course.js";
import { groupRoute } from "./group.js";
import { certificateRouter } from "./certificate.js";
import { teacherRoute } from "./teachers.js";
export const controlRoute = Router();
controlRoute.use("/student", studentRoute);
controlRoute.use("/course", courseRoute);
controlRoute.use("/group", groupRoute);
controlRoute.use("/certificate", certificateRouter);
controlRoute.use("/teachers", teacherRoute);
