import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
const comfortaa = Comfortaa({ subsets: ["latin"] });
import "@/assets/css/globals.css";
import MainHeader from "@/components/MainHeader";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <NextUIProvider>
          <MainHeader />
          {children}
          </NextUIProvider>
      </body>
    </html>
  );
}
