export { default as heroImg } from "./images/pngwing.com.png"
export { default as itCenter } from "./images/it-center.jpg"
export { default as computer } from "./images/microsoft-office.webp"
export { default as frontEnd } from "./images/font-end.webp"
export { default as english } from "./images/Evening_English.jpg"
export { default as logo } from "./images/logo.svg"
export { default as anonymous } from "./images/anonymous-mask.svg"
export { default as webAddress } from "./images/web-address-64.png"
// gifs
export { default as notFound } from "./gifs/404-animation.gif"